// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xschedule_nodma.h"

extern XSchedule_nodma_Config XSchedule_nodma_ConfigTable[];

XSchedule_nodma_Config *XSchedule_nodma_LookupConfig(u16 DeviceId) {
	XSchedule_nodma_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSCHEDULE_NODMA_NUM_INSTANCES; Index++) {
		if (XSchedule_nodma_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSchedule_nodma_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSchedule_nodma_Initialize(XSchedule_nodma *InstancePtr, u16 DeviceId) {
	XSchedule_nodma_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSchedule_nodma_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSchedule_nodma_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

