-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity compute_core_id is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    kk_i : IN STD_LOGIC_VECTOR (0 downto 0);
    kk_o : OUT STD_LOGIC_VECTOR (0 downto 0);
    kk_o_ap_vld : OUT STD_LOGIC;
    check_msg_out0_V_i_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    check_msg_out0_V_i_empty_n : IN STD_LOGIC;
    check_msg_out0_V_i_read : OUT STD_LOGIC;
    check_msg_out0_V_cor_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    check_msg_out0_V_cor_empty_n : IN STD_LOGIC;
    check_msg_out0_V_cor_read : OUT STD_LOGIC;
    check_msg_out0_V_old_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    check_msg_out0_V_old_empty_n : IN STD_LOGIC;
    check_msg_out0_V_old_read : OUT STD_LOGIC;
    check_msg_out0_V_new_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    check_msg_out0_V_new_empty_n : IN STD_LOGIC;
    check_msg_out0_V_new_read : OUT STD_LOGIC;
    check_msg_out1_V_i_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    check_msg_out1_V_i_empty_n : IN STD_LOGIC;
    check_msg_out1_V_i_read : OUT STD_LOGIC;
    check_msg_out1_V_cor_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    check_msg_out1_V_cor_empty_n : IN STD_LOGIC;
    check_msg_out1_V_cor_read : OUT STD_LOGIC;
    check_msg_out1_V_old_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    check_msg_out1_V_old_empty_n : IN STD_LOGIC;
    check_msg_out1_V_old_read : OUT STD_LOGIC;
    check_msg_out1_V_new_dout : IN STD_LOGIC_VECTOR (511 downto 0);
    check_msg_out1_V_new_empty_n : IN STD_LOGIC;
    check_msg_out1_V_new_read : OUT STD_LOGIC;
    CORE_NUM : IN STD_LOGIC_VECTOR (31 downto 0);
    bit_clusters_V_21 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_0 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_1 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_2 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_3 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_4 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_5 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_6 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_7 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_8 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_9 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_10 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_11 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_12 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_13 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_14 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_15 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_16 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_17 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_18 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_19 : IN STD_LOGIC_VECTOR (511 downto 0);
    bit_clusters_V_20 : IN STD_LOGIC_VECTOR (511 downto 0);
    merge_weights_V_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_0_ce0 : OUT STD_LOGIC;
    merge_weights_V_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_1_ce0 : OUT STD_LOGIC;
    merge_weights_V_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_2_ce0 : OUT STD_LOGIC;
    merge_weights_V_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_3_ce0 : OUT STD_LOGIC;
    merge_weights_V_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_4_ce0 : OUT STD_LOGIC;
    merge_weights_V_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_5_ce0 : OUT STD_LOGIC;
    merge_weights_V_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_6_ce0 : OUT STD_LOGIC;
    merge_weights_V_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_7_ce0 : OUT STD_LOGIC;
    merge_weights_V_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_8_ce0 : OUT STD_LOGIC;
    merge_weights_V_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_9_ce0 : OUT STD_LOGIC;
    merge_weights_V_9_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_10_ce0 : OUT STD_LOGIC;
    merge_weights_V_10_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_11_ce0 : OUT STD_LOGIC;
    merge_weights_V_11_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_12_ce0 : OUT STD_LOGIC;
    merge_weights_V_12_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_13_ce0 : OUT STD_LOGIC;
    merge_weights_V_13_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_14_ce0 : OUT STD_LOGIC;
    merge_weights_V_14_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_15_ce0 : OUT STD_LOGIC;
    merge_weights_V_15_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_16_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_16_ce0 : OUT STD_LOGIC;
    merge_weights_V_16_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_17_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_17_ce0 : OUT STD_LOGIC;
    merge_weights_V_17_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_18_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_18_ce0 : OUT STD_LOGIC;
    merge_weights_V_18_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_19_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_19_ce0 : OUT STD_LOGIC;
    merge_weights_V_19_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_20_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_20_ce0 : OUT STD_LOGIC;
    merge_weights_V_20_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_21_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_21_ce0 : OUT STD_LOGIC;
    merge_weights_V_21_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_22_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_22_ce0 : OUT STD_LOGIC;
    merge_weights_V_22_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_23_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_23_ce0 : OUT STD_LOGIC;
    merge_weights_V_23_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_24_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_24_ce0 : OUT STD_LOGIC;
    merge_weights_V_24_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_25_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_25_ce0 : OUT STD_LOGIC;
    merge_weights_V_25_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_26_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_26_ce0 : OUT STD_LOGIC;
    merge_weights_V_26_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_27_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_27_ce0 : OUT STD_LOGIC;
    merge_weights_V_27_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_28_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_28_ce0 : OUT STD_LOGIC;
    merge_weights_V_28_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_29_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_29_ce0 : OUT STD_LOGIC;
    merge_weights_V_29_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_30_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_30_ce0 : OUT STD_LOGIC;
    merge_weights_V_30_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_31_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_31_ce0 : OUT STD_LOGIC;
    merge_weights_V_31_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_32_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_32_ce0 : OUT STD_LOGIC;
    merge_weights_V_32_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_33_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_33_ce0 : OUT STD_LOGIC;
    merge_weights_V_33_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_34_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_34_ce0 : OUT STD_LOGIC;
    merge_weights_V_34_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_35_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_35_ce0 : OUT STD_LOGIC;
    merge_weights_V_35_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_36_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_36_ce0 : OUT STD_LOGIC;
    merge_weights_V_36_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_37_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_37_ce0 : OUT STD_LOGIC;
    merge_weights_V_37_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_38_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_38_ce0 : OUT STD_LOGIC;
    merge_weights_V_38_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_39_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_39_ce0 : OUT STD_LOGIC;
    merge_weights_V_39_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_40_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_40_ce0 : OUT STD_LOGIC;
    merge_weights_V_40_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_41_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_41_ce0 : OUT STD_LOGIC;
    merge_weights_V_41_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_42_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_42_ce0 : OUT STD_LOGIC;
    merge_weights_V_42_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_43_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_43_ce0 : OUT STD_LOGIC;
    merge_weights_V_43_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_44_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_44_ce0 : OUT STD_LOGIC;
    merge_weights_V_44_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_45_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_45_ce0 : OUT STD_LOGIC;
    merge_weights_V_45_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_46_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_46_ce0 : OUT STD_LOGIC;
    merge_weights_V_46_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_47_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_47_ce0 : OUT STD_LOGIC;
    merge_weights_V_47_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_48_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_48_ce0 : OUT STD_LOGIC;
    merge_weights_V_48_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_49_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_49_ce0 : OUT STD_LOGIC;
    merge_weights_V_49_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_50_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_50_ce0 : OUT STD_LOGIC;
    merge_weights_V_50_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_51_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_51_ce0 : OUT STD_LOGIC;
    merge_weights_V_51_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_52_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_52_ce0 : OUT STD_LOGIC;
    merge_weights_V_52_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_53_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_53_ce0 : OUT STD_LOGIC;
    merge_weights_V_53_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_54_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_54_ce0 : OUT STD_LOGIC;
    merge_weights_V_54_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_55_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_55_ce0 : OUT STD_LOGIC;
    merge_weights_V_55_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_56_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_56_ce0 : OUT STD_LOGIC;
    merge_weights_V_56_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_57_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_57_ce0 : OUT STD_LOGIC;
    merge_weights_V_57_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_58_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_58_ce0 : OUT STD_LOGIC;
    merge_weights_V_58_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_59_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_59_ce0 : OUT STD_LOGIC;
    merge_weights_V_59_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_60_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_60_ce0 : OUT STD_LOGIC;
    merge_weights_V_60_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_61_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_61_ce0 : OUT STD_LOGIC;
    merge_weights_V_61_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_62_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_62_ce0 : OUT STD_LOGIC;
    merge_weights_V_62_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_63_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    merge_weights_V_63_ce0 : OUT STD_LOGIC;
    merge_weights_V_63_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    compute_core_id_out_s_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    compute_core_id_out_s_1_full_n : IN STD_LOGIC;
    compute_core_id_out_s_1_write : OUT STD_LOGIC;
    compute_core_id_out_1_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    compute_core_id_out_1_0_full_n : IN STD_LOGIC;
    compute_core_id_out_1_0_write : OUT STD_LOGIC;
    update_cluster_in_V_s_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    update_cluster_in_V_s_full_n : IN STD_LOGIC;
    update_cluster_in_V_s_write : OUT STD_LOGIC;
    update_cluster_in_V_4_din : OUT STD_LOGIC_VECTOR (511 downto 0);
    update_cluster_in_V_4_full_n : IN STD_LOGIC;
    update_cluster_in_V_4_write : OUT STD_LOGIC;
    update_cluster_in_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    update_cluster_in_V_3_full_n : IN STD_LOGIC;
    update_cluster_in_V_3_write : OUT STD_LOGIC;
    update_cluster_in_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    update_cluster_in_V_1_full_n : IN STD_LOGIC;
    update_cluster_in_V_1_write : OUT STD_LOGIC );
end;


architecture behav of compute_core_id is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal check_msg_out0_V_i_blk_n : STD_LOGIC;
    signal tmp_nbreadreq_fu_228_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal check_msg_out0_V_cor_blk_n : STD_LOGIC;
    signal check_msg_out0_V_old_blk_n : STD_LOGIC;
    signal check_msg_out0_V_new_blk_n : STD_LOGIC;
    signal check_msg_out1_V_i_blk_n : STD_LOGIC;
    signal tmp_1_nbreadreq_fu_254_p6 : STD_LOGIC_VECTOR (0 downto 0);
    signal check_msg_out1_V_cor_blk_n : STD_LOGIC;
    signal check_msg_out1_V_old_blk_n : STD_LOGIC;
    signal check_msg_out1_V_new_blk_n : STD_LOGIC;
    signal kk_load_reg_566 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal check_msg_out0_V_i0_status : STD_LOGIC;
    signal ap_predicate_op24_read_state1 : BOOLEAN;
    signal check_msg_out1_V_i0_status : STD_LOGIC;
    signal ap_predicate_op34_read_state1 : BOOLEAN;
    signal ap_block_state1 : BOOLEAN;
    signal tmp_reg_570 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal tmp_1_reg_594 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal grp_core_id_func_fu_320_ap_start : STD_LOGIC;
    signal grp_core_id_func_fu_320_ap_done : STD_LOGIC;
    signal grp_core_id_func_fu_320_ap_idle : STD_LOGIC;
    signal grp_core_id_func_fu_320_ap_ready : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_0_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_1_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_2_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_2_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_3_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_3_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_4_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_4_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_5_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_5_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_6_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_6_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_7_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_7_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_8_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_8_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_9_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_9_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_10_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_10_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_11_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_11_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_12_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_12_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_13_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_13_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_14_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_14_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_15_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_15_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_16_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_16_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_17_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_17_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_18_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_18_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_19_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_19_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_20_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_20_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_21_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_21_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_22_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_22_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_23_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_23_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_24_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_24_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_25_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_25_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_26_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_26_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_27_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_27_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_28_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_28_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_29_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_29_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_30_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_30_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_31_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_31_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_32_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_32_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_33_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_33_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_34_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_34_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_35_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_35_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_36_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_36_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_37_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_37_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_38_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_38_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_39_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_39_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_40_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_40_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_41_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_41_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_42_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_42_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_43_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_43_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_44_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_44_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_45_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_45_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_46_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_46_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_47_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_47_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_48_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_48_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_49_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_49_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_50_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_50_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_51_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_51_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_52_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_52_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_53_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_53_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_54_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_54_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_55_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_55_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_56_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_56_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_57_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_57_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_58_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_58_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_59_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_59_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_60_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_60_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_61_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_61_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_62_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_62_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_merge_weights_V_63_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_core_id_func_fu_320_merge_weights_V_63_ce0 : STD_LOGIC;
    signal grp_core_id_func_fu_320_compute_core_id_out_s_1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_id_func_fu_320_compute_core_id_out_s_1_write : STD_LOGIC;
    signal grp_core_id_func_fu_320_compute_core_id_out_1_0_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_id_func_fu_320_compute_core_id_out_1_0_write : STD_LOGIC;
    signal grp_core_id_func_fu_320_update_cluster_in_V_s_din : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_core_id_func_fu_320_update_cluster_in_V_s_write : STD_LOGIC;
    signal grp_core_id_func_fu_320_update_cluster_in_V_4_din : STD_LOGIC_VECTOR (511 downto 0);
    signal grp_core_id_func_fu_320_update_cluster_in_V_4_write : STD_LOGIC;
    signal grp_core_id_func_fu_320_update_cluster_in_V_3_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_id_func_fu_320_update_cluster_in_V_3_write : STD_LOGIC;
    signal grp_core_id_func_fu_320_update_cluster_in_V_1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_core_id_func_fu_320_update_cluster_in_V_1_write : STD_LOGIC;
    signal p_3_i_reg_280 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal p_2_i_reg_290 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal p_1_i_reg_300 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_0_i_reg_310 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal grp_core_id_func_fu_320_ap_start_reg : STD_LOGIC := '0';
    signal check_msg_out0_V_i0_update : STD_LOGIC;
    signal check_msg_out1_V_i0_update : STD_LOGIC;
    signal ap_predicate_op45_call_state3 : BOOLEAN;
    signal ap_block_state3_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_condition_528 : BOOLEAN;

    component core_id_func IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        msg_i : IN STD_LOGIC_VECTOR (31 downto 0);
        msg_core_id : IN STD_LOGIC_VECTOR (31 downto 0);
        msg_old_features_V : IN STD_LOGIC_VECTOR (511 downto 0);
        msg_new_features_V : IN STD_LOGIC_VECTOR (511 downto 0);
        CORE_NUM : IN STD_LOGIC_VECTOR (31 downto 0);
        bit_clusters_V_21 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_0 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_1 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_2 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_3 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_4 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_5 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_6 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_7 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_8 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_9 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_10 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_11 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_12 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_13 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_14 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_15 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_16 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_17 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_18 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_19 : IN STD_LOGIC_VECTOR (511 downto 0);
        bit_clusters_V_20 : IN STD_LOGIC_VECTOR (511 downto 0);
        merge_weights_V_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_0_ce0 : OUT STD_LOGIC;
        merge_weights_V_0_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_1_ce0 : OUT STD_LOGIC;
        merge_weights_V_1_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_2_ce0 : OUT STD_LOGIC;
        merge_weights_V_2_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_3_ce0 : OUT STD_LOGIC;
        merge_weights_V_3_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_4_ce0 : OUT STD_LOGIC;
        merge_weights_V_4_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_5_ce0 : OUT STD_LOGIC;
        merge_weights_V_5_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_6_ce0 : OUT STD_LOGIC;
        merge_weights_V_6_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_7_ce0 : OUT STD_LOGIC;
        merge_weights_V_7_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_8_ce0 : OUT STD_LOGIC;
        merge_weights_V_8_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_9_ce0 : OUT STD_LOGIC;
        merge_weights_V_9_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_10_ce0 : OUT STD_LOGIC;
        merge_weights_V_10_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_11_ce0 : OUT STD_LOGIC;
        merge_weights_V_11_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_12_ce0 : OUT STD_LOGIC;
        merge_weights_V_12_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_13_ce0 : OUT STD_LOGIC;
        merge_weights_V_13_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_14_ce0 : OUT STD_LOGIC;
        merge_weights_V_14_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_15_ce0 : OUT STD_LOGIC;
        merge_weights_V_15_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_16_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_16_ce0 : OUT STD_LOGIC;
        merge_weights_V_16_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_17_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_17_ce0 : OUT STD_LOGIC;
        merge_weights_V_17_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_18_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_18_ce0 : OUT STD_LOGIC;
        merge_weights_V_18_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_19_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_19_ce0 : OUT STD_LOGIC;
        merge_weights_V_19_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_20_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_20_ce0 : OUT STD_LOGIC;
        merge_weights_V_20_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_21_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_21_ce0 : OUT STD_LOGIC;
        merge_weights_V_21_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_22_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_22_ce0 : OUT STD_LOGIC;
        merge_weights_V_22_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_23_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_23_ce0 : OUT STD_LOGIC;
        merge_weights_V_23_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_24_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_24_ce0 : OUT STD_LOGIC;
        merge_weights_V_24_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_25_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_25_ce0 : OUT STD_LOGIC;
        merge_weights_V_25_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_26_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_26_ce0 : OUT STD_LOGIC;
        merge_weights_V_26_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_27_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_27_ce0 : OUT STD_LOGIC;
        merge_weights_V_27_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_28_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_28_ce0 : OUT STD_LOGIC;
        merge_weights_V_28_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_29_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_29_ce0 : OUT STD_LOGIC;
        merge_weights_V_29_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_30_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_30_ce0 : OUT STD_LOGIC;
        merge_weights_V_30_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_31_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_31_ce0 : OUT STD_LOGIC;
        merge_weights_V_31_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_32_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_32_ce0 : OUT STD_LOGIC;
        merge_weights_V_32_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_33_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_33_ce0 : OUT STD_LOGIC;
        merge_weights_V_33_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_34_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_34_ce0 : OUT STD_LOGIC;
        merge_weights_V_34_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_35_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_35_ce0 : OUT STD_LOGIC;
        merge_weights_V_35_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_36_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_36_ce0 : OUT STD_LOGIC;
        merge_weights_V_36_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_37_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_37_ce0 : OUT STD_LOGIC;
        merge_weights_V_37_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_38_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_38_ce0 : OUT STD_LOGIC;
        merge_weights_V_38_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_39_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_39_ce0 : OUT STD_LOGIC;
        merge_weights_V_39_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_40_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_40_ce0 : OUT STD_LOGIC;
        merge_weights_V_40_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_41_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_41_ce0 : OUT STD_LOGIC;
        merge_weights_V_41_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_42_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_42_ce0 : OUT STD_LOGIC;
        merge_weights_V_42_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_43_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_43_ce0 : OUT STD_LOGIC;
        merge_weights_V_43_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_44_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_44_ce0 : OUT STD_LOGIC;
        merge_weights_V_44_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_45_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_45_ce0 : OUT STD_LOGIC;
        merge_weights_V_45_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_46_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_46_ce0 : OUT STD_LOGIC;
        merge_weights_V_46_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_47_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_47_ce0 : OUT STD_LOGIC;
        merge_weights_V_47_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_48_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_48_ce0 : OUT STD_LOGIC;
        merge_weights_V_48_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_49_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_49_ce0 : OUT STD_LOGIC;
        merge_weights_V_49_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_50_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_50_ce0 : OUT STD_LOGIC;
        merge_weights_V_50_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_51_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_51_ce0 : OUT STD_LOGIC;
        merge_weights_V_51_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_52_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_52_ce0 : OUT STD_LOGIC;
        merge_weights_V_52_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_53_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_53_ce0 : OUT STD_LOGIC;
        merge_weights_V_53_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_54_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_54_ce0 : OUT STD_LOGIC;
        merge_weights_V_54_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_55_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_55_ce0 : OUT STD_LOGIC;
        merge_weights_V_55_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_56_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_56_ce0 : OUT STD_LOGIC;
        merge_weights_V_56_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_57_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_57_ce0 : OUT STD_LOGIC;
        merge_weights_V_57_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_58_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_58_ce0 : OUT STD_LOGIC;
        merge_weights_V_58_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_59_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_59_ce0 : OUT STD_LOGIC;
        merge_weights_V_59_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_60_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_60_ce0 : OUT STD_LOGIC;
        merge_weights_V_60_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_61_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_61_ce0 : OUT STD_LOGIC;
        merge_weights_V_61_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_62_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_62_ce0 : OUT STD_LOGIC;
        merge_weights_V_62_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_63_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        merge_weights_V_63_ce0 : OUT STD_LOGIC;
        merge_weights_V_63_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        compute_core_id_out_s_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compute_core_id_out_s_1_full_n : IN STD_LOGIC;
        compute_core_id_out_s_1_write : OUT STD_LOGIC;
        compute_core_id_out_1_0_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        compute_core_id_out_1_0_full_n : IN STD_LOGIC;
        compute_core_id_out_1_0_write : OUT STD_LOGIC;
        update_cluster_in_V_s_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        update_cluster_in_V_s_full_n : IN STD_LOGIC;
        update_cluster_in_V_s_write : OUT STD_LOGIC;
        update_cluster_in_V_4_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        update_cluster_in_V_4_full_n : IN STD_LOGIC;
        update_cluster_in_V_4_write : OUT STD_LOGIC;
        update_cluster_in_V_3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        update_cluster_in_V_3_full_n : IN STD_LOGIC;
        update_cluster_in_V_3_write : OUT STD_LOGIC;
        update_cluster_in_V_1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        update_cluster_in_V_1_full_n : IN STD_LOGIC;
        update_cluster_in_V_1_write : OUT STD_LOGIC );
    end component;



begin
    grp_core_id_func_fu_320 : component core_id_func
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_core_id_func_fu_320_ap_start,
        ap_done => grp_core_id_func_fu_320_ap_done,
        ap_idle => grp_core_id_func_fu_320_ap_idle,
        ap_ready => grp_core_id_func_fu_320_ap_ready,
        msg_i => p_0_i_reg_310,
        msg_core_id => p_1_i_reg_300,
        msg_old_features_V => p_2_i_reg_290,
        msg_new_features_V => p_3_i_reg_280,
        CORE_NUM => CORE_NUM,
        bit_clusters_V_21 => bit_clusters_V_21,
        bit_clusters_V_0 => bit_clusters_V_0,
        bit_clusters_V_1 => bit_clusters_V_1,
        bit_clusters_V_2 => bit_clusters_V_2,
        bit_clusters_V_3 => bit_clusters_V_3,
        bit_clusters_V_4 => bit_clusters_V_4,
        bit_clusters_V_5 => bit_clusters_V_5,
        bit_clusters_V_6 => bit_clusters_V_6,
        bit_clusters_V_7 => bit_clusters_V_7,
        bit_clusters_V_8 => bit_clusters_V_8,
        bit_clusters_V_9 => bit_clusters_V_9,
        bit_clusters_V_10 => bit_clusters_V_10,
        bit_clusters_V_11 => bit_clusters_V_11,
        bit_clusters_V_12 => bit_clusters_V_12,
        bit_clusters_V_13 => bit_clusters_V_13,
        bit_clusters_V_14 => bit_clusters_V_14,
        bit_clusters_V_15 => bit_clusters_V_15,
        bit_clusters_V_16 => bit_clusters_V_16,
        bit_clusters_V_17 => bit_clusters_V_17,
        bit_clusters_V_18 => bit_clusters_V_18,
        bit_clusters_V_19 => bit_clusters_V_19,
        bit_clusters_V_20 => bit_clusters_V_20,
        merge_weights_V_0_address0 => grp_core_id_func_fu_320_merge_weights_V_0_address0,
        merge_weights_V_0_ce0 => grp_core_id_func_fu_320_merge_weights_V_0_ce0,
        merge_weights_V_0_q0 => merge_weights_V_0_q0,
        merge_weights_V_1_address0 => grp_core_id_func_fu_320_merge_weights_V_1_address0,
        merge_weights_V_1_ce0 => grp_core_id_func_fu_320_merge_weights_V_1_ce0,
        merge_weights_V_1_q0 => merge_weights_V_1_q0,
        merge_weights_V_2_address0 => grp_core_id_func_fu_320_merge_weights_V_2_address0,
        merge_weights_V_2_ce0 => grp_core_id_func_fu_320_merge_weights_V_2_ce0,
        merge_weights_V_2_q0 => merge_weights_V_2_q0,
        merge_weights_V_3_address0 => grp_core_id_func_fu_320_merge_weights_V_3_address0,
        merge_weights_V_3_ce0 => grp_core_id_func_fu_320_merge_weights_V_3_ce0,
        merge_weights_V_3_q0 => merge_weights_V_3_q0,
        merge_weights_V_4_address0 => grp_core_id_func_fu_320_merge_weights_V_4_address0,
        merge_weights_V_4_ce0 => grp_core_id_func_fu_320_merge_weights_V_4_ce0,
        merge_weights_V_4_q0 => merge_weights_V_4_q0,
        merge_weights_V_5_address0 => grp_core_id_func_fu_320_merge_weights_V_5_address0,
        merge_weights_V_5_ce0 => grp_core_id_func_fu_320_merge_weights_V_5_ce0,
        merge_weights_V_5_q0 => merge_weights_V_5_q0,
        merge_weights_V_6_address0 => grp_core_id_func_fu_320_merge_weights_V_6_address0,
        merge_weights_V_6_ce0 => grp_core_id_func_fu_320_merge_weights_V_6_ce0,
        merge_weights_V_6_q0 => merge_weights_V_6_q0,
        merge_weights_V_7_address0 => grp_core_id_func_fu_320_merge_weights_V_7_address0,
        merge_weights_V_7_ce0 => grp_core_id_func_fu_320_merge_weights_V_7_ce0,
        merge_weights_V_7_q0 => merge_weights_V_7_q0,
        merge_weights_V_8_address0 => grp_core_id_func_fu_320_merge_weights_V_8_address0,
        merge_weights_V_8_ce0 => grp_core_id_func_fu_320_merge_weights_V_8_ce0,
        merge_weights_V_8_q0 => merge_weights_V_8_q0,
        merge_weights_V_9_address0 => grp_core_id_func_fu_320_merge_weights_V_9_address0,
        merge_weights_V_9_ce0 => grp_core_id_func_fu_320_merge_weights_V_9_ce0,
        merge_weights_V_9_q0 => merge_weights_V_9_q0,
        merge_weights_V_10_address0 => grp_core_id_func_fu_320_merge_weights_V_10_address0,
        merge_weights_V_10_ce0 => grp_core_id_func_fu_320_merge_weights_V_10_ce0,
        merge_weights_V_10_q0 => merge_weights_V_10_q0,
        merge_weights_V_11_address0 => grp_core_id_func_fu_320_merge_weights_V_11_address0,
        merge_weights_V_11_ce0 => grp_core_id_func_fu_320_merge_weights_V_11_ce0,
        merge_weights_V_11_q0 => merge_weights_V_11_q0,
        merge_weights_V_12_address0 => grp_core_id_func_fu_320_merge_weights_V_12_address0,
        merge_weights_V_12_ce0 => grp_core_id_func_fu_320_merge_weights_V_12_ce0,
        merge_weights_V_12_q0 => merge_weights_V_12_q0,
        merge_weights_V_13_address0 => grp_core_id_func_fu_320_merge_weights_V_13_address0,
        merge_weights_V_13_ce0 => grp_core_id_func_fu_320_merge_weights_V_13_ce0,
        merge_weights_V_13_q0 => merge_weights_V_13_q0,
        merge_weights_V_14_address0 => grp_core_id_func_fu_320_merge_weights_V_14_address0,
        merge_weights_V_14_ce0 => grp_core_id_func_fu_320_merge_weights_V_14_ce0,
        merge_weights_V_14_q0 => merge_weights_V_14_q0,
        merge_weights_V_15_address0 => grp_core_id_func_fu_320_merge_weights_V_15_address0,
        merge_weights_V_15_ce0 => grp_core_id_func_fu_320_merge_weights_V_15_ce0,
        merge_weights_V_15_q0 => merge_weights_V_15_q0,
        merge_weights_V_16_address0 => grp_core_id_func_fu_320_merge_weights_V_16_address0,
        merge_weights_V_16_ce0 => grp_core_id_func_fu_320_merge_weights_V_16_ce0,
        merge_weights_V_16_q0 => merge_weights_V_16_q0,
        merge_weights_V_17_address0 => grp_core_id_func_fu_320_merge_weights_V_17_address0,
        merge_weights_V_17_ce0 => grp_core_id_func_fu_320_merge_weights_V_17_ce0,
        merge_weights_V_17_q0 => merge_weights_V_17_q0,
        merge_weights_V_18_address0 => grp_core_id_func_fu_320_merge_weights_V_18_address0,
        merge_weights_V_18_ce0 => grp_core_id_func_fu_320_merge_weights_V_18_ce0,
        merge_weights_V_18_q0 => merge_weights_V_18_q0,
        merge_weights_V_19_address0 => grp_core_id_func_fu_320_merge_weights_V_19_address0,
        merge_weights_V_19_ce0 => grp_core_id_func_fu_320_merge_weights_V_19_ce0,
        merge_weights_V_19_q0 => merge_weights_V_19_q0,
        merge_weights_V_20_address0 => grp_core_id_func_fu_320_merge_weights_V_20_address0,
        merge_weights_V_20_ce0 => grp_core_id_func_fu_320_merge_weights_V_20_ce0,
        merge_weights_V_20_q0 => merge_weights_V_20_q0,
        merge_weights_V_21_address0 => grp_core_id_func_fu_320_merge_weights_V_21_address0,
        merge_weights_V_21_ce0 => grp_core_id_func_fu_320_merge_weights_V_21_ce0,
        merge_weights_V_21_q0 => merge_weights_V_21_q0,
        merge_weights_V_22_address0 => grp_core_id_func_fu_320_merge_weights_V_22_address0,
        merge_weights_V_22_ce0 => grp_core_id_func_fu_320_merge_weights_V_22_ce0,
        merge_weights_V_22_q0 => merge_weights_V_22_q0,
        merge_weights_V_23_address0 => grp_core_id_func_fu_320_merge_weights_V_23_address0,
        merge_weights_V_23_ce0 => grp_core_id_func_fu_320_merge_weights_V_23_ce0,
        merge_weights_V_23_q0 => merge_weights_V_23_q0,
        merge_weights_V_24_address0 => grp_core_id_func_fu_320_merge_weights_V_24_address0,
        merge_weights_V_24_ce0 => grp_core_id_func_fu_320_merge_weights_V_24_ce0,
        merge_weights_V_24_q0 => merge_weights_V_24_q0,
        merge_weights_V_25_address0 => grp_core_id_func_fu_320_merge_weights_V_25_address0,
        merge_weights_V_25_ce0 => grp_core_id_func_fu_320_merge_weights_V_25_ce0,
        merge_weights_V_25_q0 => merge_weights_V_25_q0,
        merge_weights_V_26_address0 => grp_core_id_func_fu_320_merge_weights_V_26_address0,
        merge_weights_V_26_ce0 => grp_core_id_func_fu_320_merge_weights_V_26_ce0,
        merge_weights_V_26_q0 => merge_weights_V_26_q0,
        merge_weights_V_27_address0 => grp_core_id_func_fu_320_merge_weights_V_27_address0,
        merge_weights_V_27_ce0 => grp_core_id_func_fu_320_merge_weights_V_27_ce0,
        merge_weights_V_27_q0 => merge_weights_V_27_q0,
        merge_weights_V_28_address0 => grp_core_id_func_fu_320_merge_weights_V_28_address0,
        merge_weights_V_28_ce0 => grp_core_id_func_fu_320_merge_weights_V_28_ce0,
        merge_weights_V_28_q0 => merge_weights_V_28_q0,
        merge_weights_V_29_address0 => grp_core_id_func_fu_320_merge_weights_V_29_address0,
        merge_weights_V_29_ce0 => grp_core_id_func_fu_320_merge_weights_V_29_ce0,
        merge_weights_V_29_q0 => merge_weights_V_29_q0,
        merge_weights_V_30_address0 => grp_core_id_func_fu_320_merge_weights_V_30_address0,
        merge_weights_V_30_ce0 => grp_core_id_func_fu_320_merge_weights_V_30_ce0,
        merge_weights_V_30_q0 => merge_weights_V_30_q0,
        merge_weights_V_31_address0 => grp_core_id_func_fu_320_merge_weights_V_31_address0,
        merge_weights_V_31_ce0 => grp_core_id_func_fu_320_merge_weights_V_31_ce0,
        merge_weights_V_31_q0 => merge_weights_V_31_q0,
        merge_weights_V_32_address0 => grp_core_id_func_fu_320_merge_weights_V_32_address0,
        merge_weights_V_32_ce0 => grp_core_id_func_fu_320_merge_weights_V_32_ce0,
        merge_weights_V_32_q0 => merge_weights_V_32_q0,
        merge_weights_V_33_address0 => grp_core_id_func_fu_320_merge_weights_V_33_address0,
        merge_weights_V_33_ce0 => grp_core_id_func_fu_320_merge_weights_V_33_ce0,
        merge_weights_V_33_q0 => merge_weights_V_33_q0,
        merge_weights_V_34_address0 => grp_core_id_func_fu_320_merge_weights_V_34_address0,
        merge_weights_V_34_ce0 => grp_core_id_func_fu_320_merge_weights_V_34_ce0,
        merge_weights_V_34_q0 => merge_weights_V_34_q0,
        merge_weights_V_35_address0 => grp_core_id_func_fu_320_merge_weights_V_35_address0,
        merge_weights_V_35_ce0 => grp_core_id_func_fu_320_merge_weights_V_35_ce0,
        merge_weights_V_35_q0 => merge_weights_V_35_q0,
        merge_weights_V_36_address0 => grp_core_id_func_fu_320_merge_weights_V_36_address0,
        merge_weights_V_36_ce0 => grp_core_id_func_fu_320_merge_weights_V_36_ce0,
        merge_weights_V_36_q0 => merge_weights_V_36_q0,
        merge_weights_V_37_address0 => grp_core_id_func_fu_320_merge_weights_V_37_address0,
        merge_weights_V_37_ce0 => grp_core_id_func_fu_320_merge_weights_V_37_ce0,
        merge_weights_V_37_q0 => merge_weights_V_37_q0,
        merge_weights_V_38_address0 => grp_core_id_func_fu_320_merge_weights_V_38_address0,
        merge_weights_V_38_ce0 => grp_core_id_func_fu_320_merge_weights_V_38_ce0,
        merge_weights_V_38_q0 => merge_weights_V_38_q0,
        merge_weights_V_39_address0 => grp_core_id_func_fu_320_merge_weights_V_39_address0,
        merge_weights_V_39_ce0 => grp_core_id_func_fu_320_merge_weights_V_39_ce0,
        merge_weights_V_39_q0 => merge_weights_V_39_q0,
        merge_weights_V_40_address0 => grp_core_id_func_fu_320_merge_weights_V_40_address0,
        merge_weights_V_40_ce0 => grp_core_id_func_fu_320_merge_weights_V_40_ce0,
        merge_weights_V_40_q0 => merge_weights_V_40_q0,
        merge_weights_V_41_address0 => grp_core_id_func_fu_320_merge_weights_V_41_address0,
        merge_weights_V_41_ce0 => grp_core_id_func_fu_320_merge_weights_V_41_ce0,
        merge_weights_V_41_q0 => merge_weights_V_41_q0,
        merge_weights_V_42_address0 => grp_core_id_func_fu_320_merge_weights_V_42_address0,
        merge_weights_V_42_ce0 => grp_core_id_func_fu_320_merge_weights_V_42_ce0,
        merge_weights_V_42_q0 => merge_weights_V_42_q0,
        merge_weights_V_43_address0 => grp_core_id_func_fu_320_merge_weights_V_43_address0,
        merge_weights_V_43_ce0 => grp_core_id_func_fu_320_merge_weights_V_43_ce0,
        merge_weights_V_43_q0 => merge_weights_V_43_q0,
        merge_weights_V_44_address0 => grp_core_id_func_fu_320_merge_weights_V_44_address0,
        merge_weights_V_44_ce0 => grp_core_id_func_fu_320_merge_weights_V_44_ce0,
        merge_weights_V_44_q0 => merge_weights_V_44_q0,
        merge_weights_V_45_address0 => grp_core_id_func_fu_320_merge_weights_V_45_address0,
        merge_weights_V_45_ce0 => grp_core_id_func_fu_320_merge_weights_V_45_ce0,
        merge_weights_V_45_q0 => merge_weights_V_45_q0,
        merge_weights_V_46_address0 => grp_core_id_func_fu_320_merge_weights_V_46_address0,
        merge_weights_V_46_ce0 => grp_core_id_func_fu_320_merge_weights_V_46_ce0,
        merge_weights_V_46_q0 => merge_weights_V_46_q0,
        merge_weights_V_47_address0 => grp_core_id_func_fu_320_merge_weights_V_47_address0,
        merge_weights_V_47_ce0 => grp_core_id_func_fu_320_merge_weights_V_47_ce0,
        merge_weights_V_47_q0 => merge_weights_V_47_q0,
        merge_weights_V_48_address0 => grp_core_id_func_fu_320_merge_weights_V_48_address0,
        merge_weights_V_48_ce0 => grp_core_id_func_fu_320_merge_weights_V_48_ce0,
        merge_weights_V_48_q0 => merge_weights_V_48_q0,
        merge_weights_V_49_address0 => grp_core_id_func_fu_320_merge_weights_V_49_address0,
        merge_weights_V_49_ce0 => grp_core_id_func_fu_320_merge_weights_V_49_ce0,
        merge_weights_V_49_q0 => merge_weights_V_49_q0,
        merge_weights_V_50_address0 => grp_core_id_func_fu_320_merge_weights_V_50_address0,
        merge_weights_V_50_ce0 => grp_core_id_func_fu_320_merge_weights_V_50_ce0,
        merge_weights_V_50_q0 => merge_weights_V_50_q0,
        merge_weights_V_51_address0 => grp_core_id_func_fu_320_merge_weights_V_51_address0,
        merge_weights_V_51_ce0 => grp_core_id_func_fu_320_merge_weights_V_51_ce0,
        merge_weights_V_51_q0 => merge_weights_V_51_q0,
        merge_weights_V_52_address0 => grp_core_id_func_fu_320_merge_weights_V_52_address0,
        merge_weights_V_52_ce0 => grp_core_id_func_fu_320_merge_weights_V_52_ce0,
        merge_weights_V_52_q0 => merge_weights_V_52_q0,
        merge_weights_V_53_address0 => grp_core_id_func_fu_320_merge_weights_V_53_address0,
        merge_weights_V_53_ce0 => grp_core_id_func_fu_320_merge_weights_V_53_ce0,
        merge_weights_V_53_q0 => merge_weights_V_53_q0,
        merge_weights_V_54_address0 => grp_core_id_func_fu_320_merge_weights_V_54_address0,
        merge_weights_V_54_ce0 => grp_core_id_func_fu_320_merge_weights_V_54_ce0,
        merge_weights_V_54_q0 => merge_weights_V_54_q0,
        merge_weights_V_55_address0 => grp_core_id_func_fu_320_merge_weights_V_55_address0,
        merge_weights_V_55_ce0 => grp_core_id_func_fu_320_merge_weights_V_55_ce0,
        merge_weights_V_55_q0 => merge_weights_V_55_q0,
        merge_weights_V_56_address0 => grp_core_id_func_fu_320_merge_weights_V_56_address0,
        merge_weights_V_56_ce0 => grp_core_id_func_fu_320_merge_weights_V_56_ce0,
        merge_weights_V_56_q0 => merge_weights_V_56_q0,
        merge_weights_V_57_address0 => grp_core_id_func_fu_320_merge_weights_V_57_address0,
        merge_weights_V_57_ce0 => grp_core_id_func_fu_320_merge_weights_V_57_ce0,
        merge_weights_V_57_q0 => merge_weights_V_57_q0,
        merge_weights_V_58_address0 => grp_core_id_func_fu_320_merge_weights_V_58_address0,
        merge_weights_V_58_ce0 => grp_core_id_func_fu_320_merge_weights_V_58_ce0,
        merge_weights_V_58_q0 => merge_weights_V_58_q0,
        merge_weights_V_59_address0 => grp_core_id_func_fu_320_merge_weights_V_59_address0,
        merge_weights_V_59_ce0 => grp_core_id_func_fu_320_merge_weights_V_59_ce0,
        merge_weights_V_59_q0 => merge_weights_V_59_q0,
        merge_weights_V_60_address0 => grp_core_id_func_fu_320_merge_weights_V_60_address0,
        merge_weights_V_60_ce0 => grp_core_id_func_fu_320_merge_weights_V_60_ce0,
        merge_weights_V_60_q0 => merge_weights_V_60_q0,
        merge_weights_V_61_address0 => grp_core_id_func_fu_320_merge_weights_V_61_address0,
        merge_weights_V_61_ce0 => grp_core_id_func_fu_320_merge_weights_V_61_ce0,
        merge_weights_V_61_q0 => merge_weights_V_61_q0,
        merge_weights_V_62_address0 => grp_core_id_func_fu_320_merge_weights_V_62_address0,
        merge_weights_V_62_ce0 => grp_core_id_func_fu_320_merge_weights_V_62_ce0,
        merge_weights_V_62_q0 => merge_weights_V_62_q0,
        merge_weights_V_63_address0 => grp_core_id_func_fu_320_merge_weights_V_63_address0,
        merge_weights_V_63_ce0 => grp_core_id_func_fu_320_merge_weights_V_63_ce0,
        merge_weights_V_63_q0 => merge_weights_V_63_q0,
        compute_core_id_out_s_1_din => grp_core_id_func_fu_320_compute_core_id_out_s_1_din,
        compute_core_id_out_s_1_full_n => compute_core_id_out_s_1_full_n,
        compute_core_id_out_s_1_write => grp_core_id_func_fu_320_compute_core_id_out_s_1_write,
        compute_core_id_out_1_0_din => grp_core_id_func_fu_320_compute_core_id_out_1_0_din,
        compute_core_id_out_1_0_full_n => compute_core_id_out_1_0_full_n,
        compute_core_id_out_1_0_write => grp_core_id_func_fu_320_compute_core_id_out_1_0_write,
        update_cluster_in_V_s_din => grp_core_id_func_fu_320_update_cluster_in_V_s_din,
        update_cluster_in_V_s_full_n => update_cluster_in_V_s_full_n,
        update_cluster_in_V_s_write => grp_core_id_func_fu_320_update_cluster_in_V_s_write,
        update_cluster_in_V_4_din => grp_core_id_func_fu_320_update_cluster_in_V_4_din,
        update_cluster_in_V_4_full_n => update_cluster_in_V_4_full_n,
        update_cluster_in_V_4_write => grp_core_id_func_fu_320_update_cluster_in_V_4_write,
        update_cluster_in_V_3_din => grp_core_id_func_fu_320_update_cluster_in_V_3_din,
        update_cluster_in_V_3_full_n => update_cluster_in_V_3_full_n,
        update_cluster_in_V_3_write => grp_core_id_func_fu_320_update_cluster_in_V_3_write,
        update_cluster_in_V_1_din => grp_core_id_func_fu_320_update_cluster_in_V_1_din,
        update_cluster_in_V_1_full_n => update_cluster_in_V_1_full_n,
        update_cluster_in_V_1_write => grp_core_id_func_fu_320_update_cluster_in_V_1_write);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_ST_fsm_state3 = ap_CS_fsm))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_core_id_func_fu_320_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_core_id_func_fu_320_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_ST_fsm_state2 = ap_CS_fsm)) then 
                    grp_core_id_func_fu_320_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_core_id_func_fu_320_ap_ready = ap_const_logic_1)) then 
                    grp_core_id_func_fu_320_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    kk_load_reg_566_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                kk_load_reg_566 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
                    kk_load_reg_566 <= kk_i;
                end if; 
            end if;
        end if;
    end process;


    p_0_i_reg_310_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_0_i_reg_310 <= ap_const_lv32_0;
            else
                if ((ap_const_boolean_1 = ap_condition_528)) then
                    if (((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0))) then 
                        p_0_i_reg_310 <= check_msg_out0_V_i_dout;
                    elsif (((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1))) then 
                        p_0_i_reg_310 <= check_msg_out1_V_i_dout;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    p_1_i_reg_300_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_1_i_reg_300 <= ap_const_lv32_0;
            else
                if ((ap_const_boolean_1 = ap_condition_528)) then
                    if (((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0))) then 
                        p_1_i_reg_300 <= check_msg_out0_V_cor_dout;
                    elsif (((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1))) then 
                        p_1_i_reg_300 <= check_msg_out1_V_cor_dout;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    p_2_i_reg_290_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_2_i_reg_290 <= ap_const_lv512_lc_1;
            else
                if ((ap_const_boolean_1 = ap_condition_528)) then
                    if (((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0))) then 
                        p_2_i_reg_290 <= check_msg_out0_V_old_dout;
                    elsif (((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1))) then 
                        p_2_i_reg_290 <= check_msg_out1_V_old_dout;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    p_3_i_reg_280_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_3_i_reg_280 <= ap_const_lv512_lc_1;
            else
                if ((ap_const_boolean_1 = ap_condition_528)) then
                    if (((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0))) then 
                        p_3_i_reg_280 <= check_msg_out0_V_new_dout;
                    elsif (((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1))) then 
                        p_3_i_reg_280 <= check_msg_out1_V_new_dout;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    tmp_1_reg_594_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_1_reg_594 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (kk_i = ap_const_lv1_1) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
                    tmp_1_reg_594 <= tmp_1_nbreadreq_fu_254_p6;
                end if; 
            end if;
        end if;
    end process;


    tmp_reg_570_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                tmp_reg_570 <= ap_const_lv1_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (kk_i = ap_const_lv1_0) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
                    tmp_reg_570 <= tmp_nbreadreq_fu_228_p6;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, kk_i, tmp_nbreadreq_fu_228_p6, tmp_1_nbreadreq_fu_254_p6, check_msg_out0_V_i0_status, ap_predicate_op24_read_state1, check_msg_out1_V_i0_status, ap_predicate_op34_read_state1, ap_block_state3_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (ap_ST_fsm_state1 = ap_CS_fsm) and (((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1)) or ((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (ap_ST_fsm_state1 = ap_CS_fsm) and (((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_0) and (kk_i = ap_const_lv1_1)) or ((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_0) and (kk_i = ap_const_lv1_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_ST_fsm_state3 = ap_CS_fsm))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, check_msg_out0_V_i0_status, ap_predicate_op24_read_state1, check_msg_out1_V_i0_status, ap_predicate_op34_read_state1)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)));
    end process;


    ap_block_state3_on_subcall_done_assign_proc : process(grp_core_id_func_fu_320_ap_done, ap_predicate_op45_call_state3)
    begin
                ap_block_state3_on_subcall_done <= ((grp_core_id_func_fu_320_ap_done = ap_const_logic_0) and (ap_predicate_op45_call_state3 = ap_const_boolean_1));
    end process;


    ap_condition_528_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, check_msg_out0_V_i0_status, ap_predicate_op24_read_state1, check_msg_out1_V_i0_status, ap_predicate_op34_read_state1)
    begin
                ap_condition_528 <= (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (ap_ST_fsm_state1 = ap_CS_fsm));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_ST_fsm_state3 = ap_CS_fsm))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm)
    begin
        if (((ap_ST_fsm_state1 = ap_CS_fsm) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op24_read_state1_assign_proc : process(kk_i, tmp_nbreadreq_fu_228_p6)
    begin
                ap_predicate_op24_read_state1 <= ((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0));
    end process;


    ap_predicate_op34_read_state1_assign_proc : process(kk_i, tmp_1_nbreadreq_fu_254_p6)
    begin
                ap_predicate_op34_read_state1 <= ((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1));
    end process;


    ap_predicate_op45_call_state3_assign_proc : process(kk_load_reg_566, tmp_reg_570, tmp_1_reg_594)
    begin
                ap_predicate_op45_call_state3 <= (((tmp_1_reg_594 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_1)) or ((tmp_reg_570 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_0)));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm, ap_block_state3_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state3_on_subcall_done) and (ap_ST_fsm_state3 = ap_CS_fsm))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    check_msg_out0_V_cor_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out0_V_cor_empty_n, tmp_nbreadreq_fu_228_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out0_V_cor_blk_n <= check_msg_out0_V_cor_empty_n;
        else 
            check_msg_out0_V_cor_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out0_V_cor_read <= check_msg_out0_V_i0_update;
    check_msg_out0_V_i0_status <= (check_msg_out0_V_old_empty_n and check_msg_out0_V_new_empty_n and check_msg_out0_V_i_empty_n and check_msg_out0_V_cor_empty_n);

    check_msg_out0_V_i0_update_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, check_msg_out0_V_i0_status, ap_predicate_op24_read_state1, check_msg_out1_V_i0_status, ap_predicate_op34_read_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (ap_ST_fsm_state1 = ap_CS_fsm) and (ap_predicate_op24_read_state1 = ap_const_boolean_1))) then 
            check_msg_out0_V_i0_update <= ap_const_logic_1;
        else 
            check_msg_out0_V_i0_update <= ap_const_logic_0;
        end if; 
    end process;


    check_msg_out0_V_i_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out0_V_i_empty_n, tmp_nbreadreq_fu_228_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out0_V_i_blk_n <= check_msg_out0_V_i_empty_n;
        else 
            check_msg_out0_V_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out0_V_i_read <= check_msg_out0_V_i0_update;

    check_msg_out0_V_new_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out0_V_new_empty_n, tmp_nbreadreq_fu_228_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out0_V_new_blk_n <= check_msg_out0_V_new_empty_n;
        else 
            check_msg_out0_V_new_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out0_V_new_read <= check_msg_out0_V_i0_update;

    check_msg_out0_V_old_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out0_V_old_empty_n, tmp_nbreadreq_fu_228_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_nbreadreq_fu_228_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_0) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out0_V_old_blk_n <= check_msg_out0_V_old_empty_n;
        else 
            check_msg_out0_V_old_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out0_V_old_read <= check_msg_out0_V_i0_update;

    check_msg_out1_V_cor_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out1_V_cor_empty_n, tmp_1_nbreadreq_fu_254_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out1_V_cor_blk_n <= check_msg_out1_V_cor_empty_n;
        else 
            check_msg_out1_V_cor_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out1_V_cor_read <= check_msg_out1_V_i0_update;
    check_msg_out1_V_i0_status <= (check_msg_out1_V_old_empty_n and check_msg_out1_V_new_empty_n and check_msg_out1_V_i_empty_n and check_msg_out1_V_cor_empty_n);

    check_msg_out1_V_i0_update_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, check_msg_out0_V_i0_status, ap_predicate_op24_read_state1, check_msg_out1_V_i0_status, ap_predicate_op34_read_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (ap_ST_fsm_state1 = ap_CS_fsm) and (ap_predicate_op34_read_state1 = ap_const_boolean_1))) then 
            check_msg_out1_V_i0_update <= ap_const_logic_1;
        else 
            check_msg_out1_V_i0_update <= ap_const_logic_0;
        end if; 
    end process;


    check_msg_out1_V_i_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out1_V_i_empty_n, tmp_1_nbreadreq_fu_254_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out1_V_i_blk_n <= check_msg_out1_V_i_empty_n;
        else 
            check_msg_out1_V_i_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out1_V_i_read <= check_msg_out1_V_i0_update;

    check_msg_out1_V_new_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out1_V_new_empty_n, tmp_1_nbreadreq_fu_254_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out1_V_new_blk_n <= check_msg_out1_V_new_empty_n;
        else 
            check_msg_out1_V_new_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out1_V_new_read <= check_msg_out1_V_i0_update;

    check_msg_out1_V_old_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, check_msg_out1_V_old_empty_n, tmp_1_nbreadreq_fu_254_p6)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_1) and (kk_i = ap_const_lv1_1) and (ap_ST_fsm_state1 = ap_CS_fsm))) then 
            check_msg_out1_V_old_blk_n <= check_msg_out1_V_old_empty_n;
        else 
            check_msg_out1_V_old_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    check_msg_out1_V_old_read <= check_msg_out1_V_i0_update;
    compute_core_id_out_1_0_din <= grp_core_id_func_fu_320_compute_core_id_out_1_0_din;

    compute_core_id_out_1_0_write_assign_proc : process(ap_CS_fsm, kk_load_reg_566, tmp_reg_570, tmp_1_reg_594, grp_core_id_func_fu_320_compute_core_id_out_1_0_write)
    begin
        if (((ap_ST_fsm_state3 = ap_CS_fsm) and (((tmp_1_reg_594 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_1)) or ((tmp_reg_570 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_0))))) then 
            compute_core_id_out_1_0_write <= grp_core_id_func_fu_320_compute_core_id_out_1_0_write;
        else 
            compute_core_id_out_1_0_write <= ap_const_logic_0;
        end if; 
    end process;

    compute_core_id_out_s_1_din <= grp_core_id_func_fu_320_compute_core_id_out_s_1_din;

    compute_core_id_out_s_1_write_assign_proc : process(ap_CS_fsm, kk_load_reg_566, tmp_reg_570, tmp_1_reg_594, grp_core_id_func_fu_320_compute_core_id_out_s_1_write)
    begin
        if (((ap_ST_fsm_state3 = ap_CS_fsm) and (((tmp_1_reg_594 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_1)) or ((tmp_reg_570 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_0))))) then 
            compute_core_id_out_s_1_write <= grp_core_id_func_fu_320_compute_core_id_out_s_1_write;
        else 
            compute_core_id_out_s_1_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_core_id_func_fu_320_ap_start <= grp_core_id_func_fu_320_ap_start_reg;

    kk_o_assign_proc : process(kk_i, tmp_nbreadreq_fu_228_p6, tmp_1_nbreadreq_fu_254_p6, ap_condition_528)
    begin
        if ((ap_const_boolean_1 = ap_condition_528)) then
            if (((tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_0) and (kk_i = ap_const_lv1_1))) then 
                kk_o <= ap_const_lv1_0;
            elsif (((tmp_nbreadreq_fu_228_p6 = ap_const_lv1_0) and (kk_i = ap_const_lv1_0))) then 
                kk_o <= ap_const_lv1_1;
            else 
                kk_o <= kk_i;
            end if;
        else 
            kk_o <= kk_i;
        end if; 
    end process;


    kk_o_ap_vld_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm, kk_i, tmp_nbreadreq_fu_228_p6, tmp_1_nbreadreq_fu_254_p6, check_msg_out0_V_i0_status, ap_predicate_op24_read_state1, check_msg_out1_V_i0_status, ap_predicate_op34_read_state1)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (tmp_1_nbreadreq_fu_254_p6 = ap_const_lv1_0) and (kk_i = ap_const_lv1_1) and (ap_ST_fsm_state1 = ap_CS_fsm)) or (not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or ((check_msg_out1_V_i0_status = ap_const_logic_0) and (ap_predicate_op34_read_state1 = ap_const_boolean_1)) or ((check_msg_out0_V_i0_status = ap_const_logic_0) and (ap_predicate_op24_read_state1 = ap_const_boolean_1)))) and (tmp_nbreadreq_fu_228_p6 = ap_const_lv1_0) and (kk_i = ap_const_lv1_0) and (ap_ST_fsm_state1 = ap_CS_fsm)))) then 
            kk_o_ap_vld <= ap_const_logic_1;
        else 
            kk_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    merge_weights_V_0_address0 <= grp_core_id_func_fu_320_merge_weights_V_0_address0;
    merge_weights_V_0_ce0 <= grp_core_id_func_fu_320_merge_weights_V_0_ce0;
    merge_weights_V_10_address0 <= grp_core_id_func_fu_320_merge_weights_V_10_address0;
    merge_weights_V_10_ce0 <= grp_core_id_func_fu_320_merge_weights_V_10_ce0;
    merge_weights_V_11_address0 <= grp_core_id_func_fu_320_merge_weights_V_11_address0;
    merge_weights_V_11_ce0 <= grp_core_id_func_fu_320_merge_weights_V_11_ce0;
    merge_weights_V_12_address0 <= grp_core_id_func_fu_320_merge_weights_V_12_address0;
    merge_weights_V_12_ce0 <= grp_core_id_func_fu_320_merge_weights_V_12_ce0;
    merge_weights_V_13_address0 <= grp_core_id_func_fu_320_merge_weights_V_13_address0;
    merge_weights_V_13_ce0 <= grp_core_id_func_fu_320_merge_weights_V_13_ce0;
    merge_weights_V_14_address0 <= grp_core_id_func_fu_320_merge_weights_V_14_address0;
    merge_weights_V_14_ce0 <= grp_core_id_func_fu_320_merge_weights_V_14_ce0;
    merge_weights_V_15_address0 <= grp_core_id_func_fu_320_merge_weights_V_15_address0;
    merge_weights_V_15_ce0 <= grp_core_id_func_fu_320_merge_weights_V_15_ce0;
    merge_weights_V_16_address0 <= grp_core_id_func_fu_320_merge_weights_V_16_address0;
    merge_weights_V_16_ce0 <= grp_core_id_func_fu_320_merge_weights_V_16_ce0;
    merge_weights_V_17_address0 <= grp_core_id_func_fu_320_merge_weights_V_17_address0;
    merge_weights_V_17_ce0 <= grp_core_id_func_fu_320_merge_weights_V_17_ce0;
    merge_weights_V_18_address0 <= grp_core_id_func_fu_320_merge_weights_V_18_address0;
    merge_weights_V_18_ce0 <= grp_core_id_func_fu_320_merge_weights_V_18_ce0;
    merge_weights_V_19_address0 <= grp_core_id_func_fu_320_merge_weights_V_19_address0;
    merge_weights_V_19_ce0 <= grp_core_id_func_fu_320_merge_weights_V_19_ce0;
    merge_weights_V_1_address0 <= grp_core_id_func_fu_320_merge_weights_V_1_address0;
    merge_weights_V_1_ce0 <= grp_core_id_func_fu_320_merge_weights_V_1_ce0;
    merge_weights_V_20_address0 <= grp_core_id_func_fu_320_merge_weights_V_20_address0;
    merge_weights_V_20_ce0 <= grp_core_id_func_fu_320_merge_weights_V_20_ce0;
    merge_weights_V_21_address0 <= grp_core_id_func_fu_320_merge_weights_V_21_address0;
    merge_weights_V_21_ce0 <= grp_core_id_func_fu_320_merge_weights_V_21_ce0;
    merge_weights_V_22_address0 <= grp_core_id_func_fu_320_merge_weights_V_22_address0;
    merge_weights_V_22_ce0 <= grp_core_id_func_fu_320_merge_weights_V_22_ce0;
    merge_weights_V_23_address0 <= grp_core_id_func_fu_320_merge_weights_V_23_address0;
    merge_weights_V_23_ce0 <= grp_core_id_func_fu_320_merge_weights_V_23_ce0;
    merge_weights_V_24_address0 <= grp_core_id_func_fu_320_merge_weights_V_24_address0;
    merge_weights_V_24_ce0 <= grp_core_id_func_fu_320_merge_weights_V_24_ce0;
    merge_weights_V_25_address0 <= grp_core_id_func_fu_320_merge_weights_V_25_address0;
    merge_weights_V_25_ce0 <= grp_core_id_func_fu_320_merge_weights_V_25_ce0;
    merge_weights_V_26_address0 <= grp_core_id_func_fu_320_merge_weights_V_26_address0;
    merge_weights_V_26_ce0 <= grp_core_id_func_fu_320_merge_weights_V_26_ce0;
    merge_weights_V_27_address0 <= grp_core_id_func_fu_320_merge_weights_V_27_address0;
    merge_weights_V_27_ce0 <= grp_core_id_func_fu_320_merge_weights_V_27_ce0;
    merge_weights_V_28_address0 <= grp_core_id_func_fu_320_merge_weights_V_28_address0;
    merge_weights_V_28_ce0 <= grp_core_id_func_fu_320_merge_weights_V_28_ce0;
    merge_weights_V_29_address0 <= grp_core_id_func_fu_320_merge_weights_V_29_address0;
    merge_weights_V_29_ce0 <= grp_core_id_func_fu_320_merge_weights_V_29_ce0;
    merge_weights_V_2_address0 <= grp_core_id_func_fu_320_merge_weights_V_2_address0;
    merge_weights_V_2_ce0 <= grp_core_id_func_fu_320_merge_weights_V_2_ce0;
    merge_weights_V_30_address0 <= grp_core_id_func_fu_320_merge_weights_V_30_address0;
    merge_weights_V_30_ce0 <= grp_core_id_func_fu_320_merge_weights_V_30_ce0;
    merge_weights_V_31_address0 <= grp_core_id_func_fu_320_merge_weights_V_31_address0;
    merge_weights_V_31_ce0 <= grp_core_id_func_fu_320_merge_weights_V_31_ce0;
    merge_weights_V_32_address0 <= grp_core_id_func_fu_320_merge_weights_V_32_address0;
    merge_weights_V_32_ce0 <= grp_core_id_func_fu_320_merge_weights_V_32_ce0;
    merge_weights_V_33_address0 <= grp_core_id_func_fu_320_merge_weights_V_33_address0;
    merge_weights_V_33_ce0 <= grp_core_id_func_fu_320_merge_weights_V_33_ce0;
    merge_weights_V_34_address0 <= grp_core_id_func_fu_320_merge_weights_V_34_address0;
    merge_weights_V_34_ce0 <= grp_core_id_func_fu_320_merge_weights_V_34_ce0;
    merge_weights_V_35_address0 <= grp_core_id_func_fu_320_merge_weights_V_35_address0;
    merge_weights_V_35_ce0 <= grp_core_id_func_fu_320_merge_weights_V_35_ce0;
    merge_weights_V_36_address0 <= grp_core_id_func_fu_320_merge_weights_V_36_address0;
    merge_weights_V_36_ce0 <= grp_core_id_func_fu_320_merge_weights_V_36_ce0;
    merge_weights_V_37_address0 <= grp_core_id_func_fu_320_merge_weights_V_37_address0;
    merge_weights_V_37_ce0 <= grp_core_id_func_fu_320_merge_weights_V_37_ce0;
    merge_weights_V_38_address0 <= grp_core_id_func_fu_320_merge_weights_V_38_address0;
    merge_weights_V_38_ce0 <= grp_core_id_func_fu_320_merge_weights_V_38_ce0;
    merge_weights_V_39_address0 <= grp_core_id_func_fu_320_merge_weights_V_39_address0;
    merge_weights_V_39_ce0 <= grp_core_id_func_fu_320_merge_weights_V_39_ce0;
    merge_weights_V_3_address0 <= grp_core_id_func_fu_320_merge_weights_V_3_address0;
    merge_weights_V_3_ce0 <= grp_core_id_func_fu_320_merge_weights_V_3_ce0;
    merge_weights_V_40_address0 <= grp_core_id_func_fu_320_merge_weights_V_40_address0;
    merge_weights_V_40_ce0 <= grp_core_id_func_fu_320_merge_weights_V_40_ce0;
    merge_weights_V_41_address0 <= grp_core_id_func_fu_320_merge_weights_V_41_address0;
    merge_weights_V_41_ce0 <= grp_core_id_func_fu_320_merge_weights_V_41_ce0;
    merge_weights_V_42_address0 <= grp_core_id_func_fu_320_merge_weights_V_42_address0;
    merge_weights_V_42_ce0 <= grp_core_id_func_fu_320_merge_weights_V_42_ce0;
    merge_weights_V_43_address0 <= grp_core_id_func_fu_320_merge_weights_V_43_address0;
    merge_weights_V_43_ce0 <= grp_core_id_func_fu_320_merge_weights_V_43_ce0;
    merge_weights_V_44_address0 <= grp_core_id_func_fu_320_merge_weights_V_44_address0;
    merge_weights_V_44_ce0 <= grp_core_id_func_fu_320_merge_weights_V_44_ce0;
    merge_weights_V_45_address0 <= grp_core_id_func_fu_320_merge_weights_V_45_address0;
    merge_weights_V_45_ce0 <= grp_core_id_func_fu_320_merge_weights_V_45_ce0;
    merge_weights_V_46_address0 <= grp_core_id_func_fu_320_merge_weights_V_46_address0;
    merge_weights_V_46_ce0 <= grp_core_id_func_fu_320_merge_weights_V_46_ce0;
    merge_weights_V_47_address0 <= grp_core_id_func_fu_320_merge_weights_V_47_address0;
    merge_weights_V_47_ce0 <= grp_core_id_func_fu_320_merge_weights_V_47_ce0;
    merge_weights_V_48_address0 <= grp_core_id_func_fu_320_merge_weights_V_48_address0;
    merge_weights_V_48_ce0 <= grp_core_id_func_fu_320_merge_weights_V_48_ce0;
    merge_weights_V_49_address0 <= grp_core_id_func_fu_320_merge_weights_V_49_address0;
    merge_weights_V_49_ce0 <= grp_core_id_func_fu_320_merge_weights_V_49_ce0;
    merge_weights_V_4_address0 <= grp_core_id_func_fu_320_merge_weights_V_4_address0;
    merge_weights_V_4_ce0 <= grp_core_id_func_fu_320_merge_weights_V_4_ce0;
    merge_weights_V_50_address0 <= grp_core_id_func_fu_320_merge_weights_V_50_address0;
    merge_weights_V_50_ce0 <= grp_core_id_func_fu_320_merge_weights_V_50_ce0;
    merge_weights_V_51_address0 <= grp_core_id_func_fu_320_merge_weights_V_51_address0;
    merge_weights_V_51_ce0 <= grp_core_id_func_fu_320_merge_weights_V_51_ce0;
    merge_weights_V_52_address0 <= grp_core_id_func_fu_320_merge_weights_V_52_address0;
    merge_weights_V_52_ce0 <= grp_core_id_func_fu_320_merge_weights_V_52_ce0;
    merge_weights_V_53_address0 <= grp_core_id_func_fu_320_merge_weights_V_53_address0;
    merge_weights_V_53_ce0 <= grp_core_id_func_fu_320_merge_weights_V_53_ce0;
    merge_weights_V_54_address0 <= grp_core_id_func_fu_320_merge_weights_V_54_address0;
    merge_weights_V_54_ce0 <= grp_core_id_func_fu_320_merge_weights_V_54_ce0;
    merge_weights_V_55_address0 <= grp_core_id_func_fu_320_merge_weights_V_55_address0;
    merge_weights_V_55_ce0 <= grp_core_id_func_fu_320_merge_weights_V_55_ce0;
    merge_weights_V_56_address0 <= grp_core_id_func_fu_320_merge_weights_V_56_address0;
    merge_weights_V_56_ce0 <= grp_core_id_func_fu_320_merge_weights_V_56_ce0;
    merge_weights_V_57_address0 <= grp_core_id_func_fu_320_merge_weights_V_57_address0;
    merge_weights_V_57_ce0 <= grp_core_id_func_fu_320_merge_weights_V_57_ce0;
    merge_weights_V_58_address0 <= grp_core_id_func_fu_320_merge_weights_V_58_address0;
    merge_weights_V_58_ce0 <= grp_core_id_func_fu_320_merge_weights_V_58_ce0;
    merge_weights_V_59_address0 <= grp_core_id_func_fu_320_merge_weights_V_59_address0;
    merge_weights_V_59_ce0 <= grp_core_id_func_fu_320_merge_weights_V_59_ce0;
    merge_weights_V_5_address0 <= grp_core_id_func_fu_320_merge_weights_V_5_address0;
    merge_weights_V_5_ce0 <= grp_core_id_func_fu_320_merge_weights_V_5_ce0;
    merge_weights_V_60_address0 <= grp_core_id_func_fu_320_merge_weights_V_60_address0;
    merge_weights_V_60_ce0 <= grp_core_id_func_fu_320_merge_weights_V_60_ce0;
    merge_weights_V_61_address0 <= grp_core_id_func_fu_320_merge_weights_V_61_address0;
    merge_weights_V_61_ce0 <= grp_core_id_func_fu_320_merge_weights_V_61_ce0;
    merge_weights_V_62_address0 <= grp_core_id_func_fu_320_merge_weights_V_62_address0;
    merge_weights_V_62_ce0 <= grp_core_id_func_fu_320_merge_weights_V_62_ce0;
    merge_weights_V_63_address0 <= grp_core_id_func_fu_320_merge_weights_V_63_address0;
    merge_weights_V_63_ce0 <= grp_core_id_func_fu_320_merge_weights_V_63_ce0;
    merge_weights_V_6_address0 <= grp_core_id_func_fu_320_merge_weights_V_6_address0;
    merge_weights_V_6_ce0 <= grp_core_id_func_fu_320_merge_weights_V_6_ce0;
    merge_weights_V_7_address0 <= grp_core_id_func_fu_320_merge_weights_V_7_address0;
    merge_weights_V_7_ce0 <= grp_core_id_func_fu_320_merge_weights_V_7_ce0;
    merge_weights_V_8_address0 <= grp_core_id_func_fu_320_merge_weights_V_8_address0;
    merge_weights_V_8_ce0 <= grp_core_id_func_fu_320_merge_weights_V_8_ce0;
    merge_weights_V_9_address0 <= grp_core_id_func_fu_320_merge_weights_V_9_address0;
    merge_weights_V_9_ce0 <= grp_core_id_func_fu_320_merge_weights_V_9_ce0;
    tmp_1_nbreadreq_fu_254_p6 <= (0=>(check_msg_out1_V_old_empty_n and check_msg_out1_V_new_empty_n and check_msg_out1_V_i_empty_n and check_msg_out1_V_cor_empty_n), others=>'-');
    tmp_nbreadreq_fu_228_p6 <= (0=>(check_msg_out0_V_old_empty_n and check_msg_out0_V_new_empty_n and check_msg_out0_V_i_empty_n and check_msg_out0_V_cor_empty_n), others=>'-');
    update_cluster_in_V_1_din <= grp_core_id_func_fu_320_update_cluster_in_V_1_din;

    update_cluster_in_V_1_write_assign_proc : process(ap_CS_fsm, kk_load_reg_566, tmp_reg_570, tmp_1_reg_594, grp_core_id_func_fu_320_update_cluster_in_V_1_write)
    begin
        if (((ap_ST_fsm_state3 = ap_CS_fsm) and (((tmp_1_reg_594 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_1)) or ((tmp_reg_570 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_0))))) then 
            update_cluster_in_V_1_write <= grp_core_id_func_fu_320_update_cluster_in_V_1_write;
        else 
            update_cluster_in_V_1_write <= ap_const_logic_0;
        end if; 
    end process;

    update_cluster_in_V_3_din <= grp_core_id_func_fu_320_update_cluster_in_V_3_din;

    update_cluster_in_V_3_write_assign_proc : process(ap_CS_fsm, kk_load_reg_566, tmp_reg_570, tmp_1_reg_594, grp_core_id_func_fu_320_update_cluster_in_V_3_write)
    begin
        if (((ap_ST_fsm_state3 = ap_CS_fsm) and (((tmp_1_reg_594 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_1)) or ((tmp_reg_570 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_0))))) then 
            update_cluster_in_V_3_write <= grp_core_id_func_fu_320_update_cluster_in_V_3_write;
        else 
            update_cluster_in_V_3_write <= ap_const_logic_0;
        end if; 
    end process;

    update_cluster_in_V_4_din <= grp_core_id_func_fu_320_update_cluster_in_V_4_din;

    update_cluster_in_V_4_write_assign_proc : process(ap_CS_fsm, kk_load_reg_566, tmp_reg_570, tmp_1_reg_594, grp_core_id_func_fu_320_update_cluster_in_V_4_write)
    begin
        if (((ap_ST_fsm_state3 = ap_CS_fsm) and (((tmp_1_reg_594 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_1)) or ((tmp_reg_570 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_0))))) then 
            update_cluster_in_V_4_write <= grp_core_id_func_fu_320_update_cluster_in_V_4_write;
        else 
            update_cluster_in_V_4_write <= ap_const_logic_0;
        end if; 
    end process;

    update_cluster_in_V_s_din <= grp_core_id_func_fu_320_update_cluster_in_V_s_din;

    update_cluster_in_V_s_write_assign_proc : process(ap_CS_fsm, kk_load_reg_566, tmp_reg_570, tmp_1_reg_594, grp_core_id_func_fu_320_update_cluster_in_V_s_write)
    begin
        if (((ap_ST_fsm_state3 = ap_CS_fsm) and (((tmp_1_reg_594 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_1)) or ((tmp_reg_570 = ap_const_lv1_1) and (kk_load_reg_566 = ap_const_lv1_0))))) then 
            update_cluster_in_V_s_write <= grp_core_id_func_fu_320_update_cluster_in_V_s_write;
        else 
            update_cluster_in_V_s_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
